/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppNavbar: typeof import('./src/components/layout/AppNavbar.vue')['default']
    AppTopNav: typeof import('./src/components/AppTopNav.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElTag: typeof import('element-plus/es')['ElTag']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HistoryItem: typeof import('./src/components/history/HistoryItem.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    MdCard: typeof import('./src/components/material/MdCard.vue')['default']
    MdChip: typeof import('./src/components/material/MdChip.vue')['default']
    MdFab: typeof import('./src/components/material/MdFab.vue')['default']
    MdTopAppBar: typeof import('./src/components/material/MdTopAppBar.vue')['default']
    NewComponent: typeof import('./src/components/NewComponent.vue')['default']
    PlayerControls: typeof import('./src/components/player/PlayerControls.vue')['default']
    RecentItem: typeof import('./src/components/home/RecentItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StorageManager: typeof import('./src/components/settings/StorageManager.vue')['default']
    SubtitleList: typeof import('./src/components/player/SubtitleList.vue')['default']
    SubtitleListItem: typeof import('./src/components/player/SubtitleListItem.vue')['default']
    SubtitleOverlay: typeof import('./src/components/player/SubtitleOverlay.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    UploadCard: typeof import('./src/components/home/UploadCard.vue')['default']
    VideoCard: typeof import('./src/components/home/VideoCard.vue')['default']
    VideoControls: typeof import('./src/components/player/VideoControls.vue')['default']
    VideoList: typeof import('./src/components/home/VideoList.vue')['default']
    VideoPlayer: typeof import('./src/components/player/VideoPlayer.vue')['default']
    VideoPlayerContainer: typeof import('./src/components/player/VideoPlayerContainer.vue')['default']
    VideoToolbar: typeof import('./src/components/home/VideoToolbar.vue')['default']
    VideoUploader: typeof import('./src/components/home/VideoUploader.vue')['default']
    VocabCard: typeof import('./src/components/vocabulary/VocabCard.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
    WordPopup: typeof import('./src/components/player/WordPopup.vue')['default']
  }
}
